---
framework: jest
preRun:
     command:
        - apt update
        - apt install postgresql -y
        - apt install postgresql-contrib -y
        - postgres psql
        - npm i -g npm@7.20.0
        - npm --prefix plugins ci
        - npm --prefix plugins run create:client && npm --prefix plugins run create:server
        - npm --prefix plugins run build:packages && npm --prefix plugins run build:server
        - npm --prefix server ci
        - npm --prefix server run db:create
        - npm --prefix server run db:migrate
postMerge:
  env:
      NODE_ENV: test
  pattern: 
    - "test/services/users.service.spec.ts"
postRun:
     command:
        - node --version
version: 1.0.0
