version: 2.0
nodeVersion: 14.17.3
tier: large
postMerge:
  preRun:
     env:
       FORCE_COLOR: true
       NODE_OPTIONS: "--max-old-space-size=8096"
       LOCKBOX_MASTER_KEY: lockbox-master-key
       SECRET_KEY_BASE: secrret-key-base
       PG_HOST: localhost
       PG_PORT: 5432
       PG_USER: postgres
       PG_PASS: postgres
       PG_DB: tooljet_test
       POSTGRES_PASSWORD: postgres
       NODE_ENV: test
     command:
        - cp /usr/local/bin/bundle /home/nucleus/
        - apt update
        - apt install build-essential -y
        # - apt install postgresql -y
        # - apt install postgresql-contrib -y
        # - /etc/init.d/postgresql start
        # - su -c "psql -c \"ALTER USER postgres PASSWORD 'postgres';\"" postgres
        - npm i -g npm@7.20.0
        - npm --prefix plugins ci
        - npm --prefix plugins run create:client && npm --prefix plugins run create:server
        - npm --prefix plugins run build:packages && npm --prefix plugins run build:server
        - npm --prefix server ci
        # - npm --prefix server run db:create
        # - npm --prefix server run db:migrate
        - cp /home/nucleus/bundle /usr/local/bin/
  subModules:
      - name: server      
        path : "./server"
        pattern: 
          - "./test/services/*.ts"
        framework : jest
        preRun:
          env:
            FORCE_COLOR: true
            NODE_OPTIONS: "--max-old-space-size=8096"
            LOCKBOX_MASTER_KEY: lockbox-master-key
            SECRET_KEY_BASE: secrret-key-base
            PG_HOST: localhost
            PG_PORT: 5432
            PG_USER: postgres
            PG_PASS: postgres
            PG_DB: tooljet_test
            POSTGRES_PASSWORD: postgres
            NODE_ENV: test
          command:
            - pwd
            - cp /usr/local/bin/bundle /home/nucleus/
            - apt install postgresql -y
            - apt install postgresql-contrib build-essential -y
            - /etc/init.d/postgresql start
            - su -c "psql -c \"ALTER USER postgres PASSWORD 'postgres';\"" postgres
            - npm i -g npm@7.20.0
            - npm ci
            - npm install jest-cli
            - npm run db:create
            - npm run db:migrate
            - pwd
            - sleep 600
            - cp /home/nucleus/bundle /usr/local/bin/
            - chmod 777 /usr/local/bin/bundle
            - /usr/local/bin/bundle --ping
        configFile : "./jest.config.ts"

