---
framework: jest
preRun:
     env:
       FORCE_COLOR: true
       NODE_OPTIONS: "--max-old-space-size=4096"
       LOCKBOX_MASTER_KEY: lockbox-master-key
       SECRET_KEY_BASE: secrret-key-base
       NODE_ENV: test
       PG_HOST: localhost
       PG_PORT: 5432
       PG_USER: postgres
       PG_PASS: postgres
       PG_DB: tooljet_test
       POSTGRES_PASSWORD: postgres
     command:
        - apt update
        - apt install postgresql -y
        - apt install postgresql-contrib -y
        - /etc/init.d/postgresql start
        - npm i -g npm@7.20.0
        - npm --prefix plugins ci
        - npm --prefix plugins run create:client && npm --prefix plugins run create:server
        - npm --prefix plugins run build:packages && npm --prefix plugins run build:server
        - npm --prefix server ci
        - su - postgres -c 'npm --prefix server run db:create'
        - su - postgres -c 'npm --prefix server run db:migrate'
postMerge:
  env:
      NODE_ENV: test
  pattern: 
    - "test/services/users.service.spec.ts"
postRun:
     command:
        - node --version
version: 1.0.0
