version: 2.0
nodeVersion: 14.17.3
postMerge:
  preRun:
     env:
       FORCE_COLOR: true
       NODE_OPTIONS: "--max-old-space-size=4096"
       LOCKBOX_MASTER_KEY: lockbox-master-key
       SECRET_KEY_BASE: secrret-key-base
       PG_HOST: localhost
       PG_PORT: 5432
       PG_USER: postgres
       PG_PASS: postgres
       PG_DB: tooljet_test
       POSTGRES_PASSWORD: postgres
       NODE_ENV: test
     command:
        - apt update
        - apt install postgresql -y
        - apt install postgresql-contrib -y
        - /etc/init.d/postgresql start
        - su -c "psql -c \"ALTER USER postgres PASSWORD 'postgres';\"" postgres
        - npm i -g npm@7.20.0
        - npm --prefix plugins ci
        - npm --prefix plugins run create:client && npm --prefix plugins run create:server
        - npm --prefix plugins run build:packages && npm --prefix plugins run build:server
        - npm --prefix server ci
        - npm --prefix server run db:create
        - npm --prefix server run db:migrate
  subModules:
      - name: server      
        path : "./server"
        pattern: 
          - "./test/services/*.ts"
        framework : jest
        preRun:
          command:
             - npm ci
        configFile : "./jest.config.ts"
# ---
# framework: jest
# nodeVersion: 14.17.3
# preRun:
#      env:
#        FORCE_COLOR: true
#        NODE_OPTIONS: "--max-old-space-size=4096"
#        LOCKBOX_MASTER_KEY: lockbox-master-key
#        SECRET_KEY_BASE: secrret-key-base
#        PG_HOST: localhost
#        PG_PORT: 5432
#        PG_USER: postgres
#        PG_PASS: postgres
#        PG_DB: tooljet_test
#        POSTGRES_PASSWORD: postgres
#        NODE_ENV: test
#      command:
#         - apt update
#         - apt install postgresql -y
#         - apt install postgresql-contrib -y
#         - /etc/init.d/postgresql start
#         - su -c "psql -c \"ALTER USER postgres PASSWORD 'postgres';\"" postgres
#         - npm i -g npm@7.20.0
#         - npm install jest
#         - npm --prefix plugins ci
#         - npm --prefix plugins run create:client && npm --prefix plugins run create:server
#         - npm --prefix plugins run build:packages && npm --prefix plugins run build:server
#         - npm --prefix server ci
#         - npm --prefix server run db:create
#         - npm --prefix server run db:migrate
# postMerge:
#   env:
#       NODE_ENV: test
#   pattern: 
#     - "./server/test/controllers/app.e2e-spec.ts"
# postRun:
#      command:
#         - node --version
# version: 1.0.0
